// <auto-generated />
using System;
using GrantTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrantTest.data.migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240123014717_DefaultProducts")]
    partial class DefaultProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("GrantTest.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 1, 22, 22, 47, 17, 559, DateTimeKind.Local).AddTicks(8724),
                            Price = 499.99m,
                            ProductName = "SmartTv"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 1, 22, 22, 47, 17, 559, DateTimeKind.Local).AddTicks(8735),
                            Price = 599.99m,
                            ProductName = "Iphone"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 1, 22, 22, 47, 17, 559, DateTimeKind.Local).AddTicks(8736),
                            Price = 399.99m,
                            ProductName = "Laptop"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2024, 1, 22, 22, 47, 17, 559, DateTimeKind.Local).AddTicks(8737),
                            Price = 59.99m,
                            ProductName = "HeadSet HyperX"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2024, 1, 22, 22, 47, 17, 559, DateTimeKind.Local).AddTicks(8738),
                            Price = 49.99m,
                            ProductName = "Mouse HyperX"
                        });
                });

            modelBuilder.Entity("GrantTest.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "User1",
                            Name = "User 1",
                            Password = "1111"
                        },
                        new
                        {
                            Id = 2,
                            Login = "User2",
                            Name = "User 2",
                            Password = "2222"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
